### PR TITLE
Fix runtime metric generation

### LINKED ISSUE #4529: .NET runtime metrics reporting stale data since version 2.31.0 of Tracer
**Describe the bug**
Since the Update from `2.30.0` to `2.31.0` several runtime metrics including `runtime.dotnet.mem.committed` and `runtime.dotnet.threads.count` are reporting incorrect/stale data.
This seems to be caused by a change in `Datadog.Trace.Util.ProcessHelpers.cs` where the reference to the current process is now stored and old values are read.

**To Reproduce**
1. Start any .NET application with runtime metrics enabled
2. Observe the reported values for runtime metrics such as `runtime.dotnet.mem.committed` and `runtime.dotnet.threads.count`
3. The values never change from the initial correct value

Also, see the code snippet below.

**Expected behavior**
The runtime metrics including `runtime.dotnet.mem.committed` and `runtime.dotnet.threads.count` are reporting correct/current values

**Screenshots**
We noticed this by seeing a very drastic drop in memory usage which was obviously caused by wrong data:
image

**Runtime environment (please complete the following information):**
- Instrumentation mode: Automatic with NuGet package Datadog.Trace.Bundle
- Tracer version: > 2.31.0
- OS: tested on Ubuntu 22.04 and Windows 11. Both are affected
- CLR: .NET 7.0

**Additional context**
To understand the issue, see the following Program:
```cs
using System.Diagnostics;

var process = Process.GetCurrentProcess();
Console.WriteLine($"Reported memory usage: {process.PrivateMemorySize64}");

Console.WriteLine("Allocating a big buffer filled with random data");
var bigBuffer = new byte[1_000_000_000];
Random.Shared.NextBytes(bigBuffer);

Console.WriteLine($"Actual memory usage: {Process.GetCurrentProcess().PrivateMemorySize64}");
Console.WriteLine($"Reported memory usage: {process.PrivateMemorySize64}");

Console.WriteLine("Refreshing process data");
process.Refresh();
Console.WriteLine($"Reported memory usage: {process.PrivateMemorySize64}");
```
On my machine it produced the following output: 
```
Reported memory usage: 12689408
Allocating a big buffer filled with random data
Actual memory usage: 1017778176
Reported memory usage: 12689408
Refreshing process data
Reported memory usage: 1017798656
```
It's clear that to get the correct values, instances of `Process` should either not be stored or it's `Refresh` method must be called.

### PR DESCRIPTION
**Pull request by andrewlock**
## Summary of changes

- Fixes process runtime metrics 
- Stops sending `runtime.dotnet.mem.committed` on non-Windows for <.NET Core 3.1

## Reason for change

In #4157 we started caching the `Process` instance for performance reasons, but that meant we were no longer getting the latest runtime metrics as described in the issue #4529.

As part of working on this fix, realised that we were always sending 0 for `runtime.dotnet.mem.committed` on Linux for <.NET Core 3.1 due to [a bug in the runtime](https://github.com/dotnet/runtime/issues/23284). 

## Implementation details

Call `Refresh()` on the process before reading the runtime metrics. 

Added a check if we're using the .NET Standard binary to see if we should send `runtime.dotnet.mem.committed`. A bit annoying, but only required in the NETSTANDARD target, so didn't seem like we should always check it

## Test coverage

Updated the runtime metrics test to add a thread that allocates a bunch of memory and verify that the value changes in the runtime metrics. The test fails (as expected) before this fix, and passes with the fix.

## Other details
Fixes #4529

### CODE REVIEW

File: tracer/test/test-applications/integrations/Samples.RuntimeMetrics/Program.cs [hunk 1]
```diff
@@ -47,7 +48,19 @@ private static void GenerateEvents()
...
-                Monitor.TryEnter(SyncRoot, 500);                
+                Monitor.TryEnter(SyncRoot, 500);
+            }
+        }
+
+        private static void GenerateMemoryPressure()
+        {
+            while (true)
+            {
+                // Do some big allocating etc
```
Comment (lucaspimentel) [inline tracer/test/test-applications/integrations/Samples.RuntimeMetrics/Program.cs:59]: Can you add the reason for doing this to the comment? :)
I assume it's to ensure the "committed memory" metric used in the integration test changes over time.

**Review by zacharycmontoya — APPROVED** [review]

**Comment by andrewlock** [comment]
## Execution-Time Benchmarks Report :stopwatch:

Execution-time results for samples comparing the following branches/commits:
- [This PR (4531)](https://github.com/DataDog/dd-trace-dotnet/tree/c012d7ee6f2f7d46f3b0a267d8fb2766f61799e6)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)

Execution-time benchmarks measure the whole time it takes to execute a program. And are intended to measure the one-off costs. Cases where the execution time results for the PR are worse than latest master results are shown in **red**. The following thresholds were used for comparing the execution times:
* Welch test with statistical test for significance of **5%**
* Only results indicating a difference greater than **5%** and **5 ms** are considered.


Note that these results are based on a _single_ point-in-time result for each branch. For full results, see the [dashboard](https://ddstaging.datadoghq.com/dashboard/4qn-6fi-54p/apm-net-execution-time-benchmarks).

Graphs show the p99 interval based on the mean and StdDev of the test run, as well as the mean value of the run (shown as a diamond below the graph).
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4531) - mean (69ms)  : 65, 74
     .   : milestone, 69,
    master - mean (71ms)  : 61, 81
     .   : milestone, 71,

    section CallTarget+Inlining+NGEN
    This PR (4531) - mean (1,045ms)  : 1019, 1072
     .   : milestone, 1045,
    master - mean (1,042ms)  : 1010, 1075
     .   : milestone, 1042,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4531) - mean (107ms)  : 94, 120
     .   : milestone, 107,
    master - mean (106ms)  : 102, 109
     .   : milestone, 106,

    section CallTarget+Inlining+NGEN
    This PR (4531) - mean (732ms)  : 695, 769
     .   : milestone, 732,
    master - mean (732ms)  : 695, 769
     .   : milestone, 732,

```
```mermaid
gantt
    title Execution time (ms) FakeDbCommand (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4531) - mean (90ms)  : 84, 95
     .   : milestone, 90,
    master - mean (90ms)  : 84, 95
     .   : milestone, 90,

    section CallTarget+Inlining+NGEN
    This PR (4531) - mean (698ms)  : 675, 721
     .   : milestone, 698,
    master - mean (692ms)  : 661, 723
     .   : milestone, 692,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Framework 4.6.2) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4531) - mean (191ms)  : 185, 196
     .   : milestone, 191,
    master - mean (189ms)  : 181, 197
     .   : milestone, 189,

    section CallTarget+Inlining+NGEN
    This PR (4531) - mean (1,133ms)  : 1103, 1162
     .   : milestone, 1133,
    master - mean (1,127ms)  : 1090, 1164
     .   : milestone, 1127,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET Core 3.1) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4531) - mean (275ms)  : 268, 282
     .   : milestone, 275,
    master - mean (270ms)  : 262, 278
     .   : milestone, 270,

    section CallTarget+Inlining+NGEN
    This PR (4531) - mean (1,093ms)  : 1065, 1122
     .   : milestone, 1093,
    master - mean (1,083ms)  : 1040, 1127
     .   : milestone, 1083,

```
```mermaid
gantt
    title Execution time (ms) HttpMessageHandler (.NET 6) 
    dateFormat  X
    axisFormat %s
    todayMarker off
    section Baseline
    This PR (4531) - mean (260ms)  : 251, 269
     .   : milestone, 260,
    master - mean (261ms)  : 253, 268
     .   : milestone, 261,

    section CallTarget+Inlining+NGEN
    This PR (4531) - mean (1,048ms)  : 1013, 1083
     .   : milestone, 1048,
    master - mean (1,038ms)  : 1011, 1065
     .   : milestone, 1038,

```

**Comment by andrewlock** [comment]
## Benchmarks Report :snail:

Benchmarks for #4531 compared to [master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470): 
* 2 benchmarks are **slower**, with geometric mean 1.141
* All benchmarks have **the same** allocations


The following thresholds were used for comparing the benchmark speeds:
* Mann–Whitney U test with statistical test for significance of **5%**
* Only results indicating a difference greater than **10%** and **0.3 ns** are considered.

Allocation changes below **0.5%** are ignored.


### Benchmark details


<details><summary><strong>Benchmarks.Trace.AgentWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`WriteAndFlushEnrichedTraces`|net6.0|475μs|157ns|588ns|0| 0|0|2.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|625μs|258ns|965ns|0| 0|0|2.63&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`WriteAndFlushEnrichedTraces`|net472|805μs|265ns|991ns|0.403| 0|0|3.22&nbsp;KB|
|#4531|`WriteAndFlushEnrichedTraces`|net6.0|481μs|96ns|359ns|0| 0|0|2.62&nbsp;KB|
|#4531|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|641μs|438ns|1.7μs|0| 0|0|2.62&nbsp;KB|
|#4531|`WriteAndFlushEnrichedTraces`|net472|802μs|211ns|788ns|0.401| 0|0|3.22&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AppSecBodyBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`AllCycleSimpleBody`|net6.0|39μs|49.1ns|184ns|0.0193| 0|0|1.69&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`AllCycleSimpleBody`|netcoreapp3.1|41.5μs|56.8ns|220ns|0.0208| 0|0|1.67&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`AllCycleSimpleBody`|net472|42.8μs|10.5ns|38ns|0.258| 0|0|1.73&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`AllCycleMoreComplexBody`|net6.0|233μs|104ns|375ns|0.133| 0|0|9.26&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`AllCycleMoreComplexBody`|netcoreapp3.1|241μs|488ns|1.83μs|0.12| 0|0|9.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`AllCycleMoreComplexBody`|net472|251μs|64.1ns|240ns|1.38| 0|0|9.33&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`ObjectExtractorSimpleBody`|net6.0|131ns|0.0541ns|0.209ns|0.00397| 0|0|280&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`ObjectExtractorSimpleBody`|netcoreapp3.1|168ns|0.0847ns|0.317ns|0.00374| 0|0|272&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`ObjectExtractorSimpleBody`|net472|144ns|0.0621ns|0.241ns|0.0446| 0|0|281&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`ObjectExtractorMoreComplexBody`|net6.0|3.02μs|0.82ns|3.07ns|0.0544| 0|0|3.88&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.02μs|2.18ns|8.16ns|0.0522| 0|0|3.78&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`ObjectExtractorMoreComplexBody`|net472|4.18μs|3.21ns|12.4ns|0.618| 0.00622|0|3.89&nbsp;KB|
|#4531|`AllCycleSimpleBody`|net6.0|38.6μs|19.7ns|73.7ns|0.0192| 0|0|1.69&nbsp;KB|
|#4531|`AllCycleSimpleBody`|netcoreapp3.1|40.8μs|39.5ns|142ns|0.0203| 0|0|1.67&nbsp;KB|
|#4531|`AllCycleSimpleBody`|net472|43.4μs|56.3ns|218ns|0.254| 0|0|1.73&nbsp;KB|
|#4531|`AllCycleMoreComplexBody`|net6.0|233μs|483ns|1.87μs|0.116| 0|0|9.26&nbsp;KB|
|#4531|`AllCycleMoreComplexBody`|netcoreapp3.1|239μs|267ns|1.03μs|0| 0|0|9.16&nbsp;KB|
|#4531|`AllCycleMoreComplexBody`|net472|248μs|67.3ns|261ns|1.36| 0|0|9.33&nbsp;KB|
|#4531|`ObjectExtractorSimpleBody`|net6.0|120ns|0.0371ns|0.139ns|0.00396| 0|0|280&nbsp;B|
|#4531|`ObjectExtractorSimpleBody`|netcoreapp3.1|174ns|0.191ns|0.74ns|0.00374| 0|0|272&nbsp;B|
|#4531|`ObjectExtractorSimpleBody`|net472|144ns|0.148ns|0.574ns|0.0446| 0|0|281&nbsp;B|
|#4531|`ObjectExtractorMoreComplexBody`|net6.0|2.95μs|0.99ns|3.83ns|0.0545| 0|0|3.88&nbsp;KB|
|#4531|`ObjectExtractorMoreComplexBody`|netcoreapp3.1|4.11μs|2.06ns|7.99ns|0.0514| 0|0|3.78&nbsp;KB|
|#4531|`ObjectExtractorMoreComplexBody`|net472|4.16μs|1.85ns|6.94ns|0.618| 0.00625|0|3.89&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.AspNetCoreBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`SendRequest`|net6.0|170μs|152ns|589ns|0.254| 0|0|18.09&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`SendRequest`|netcoreapp3.1|191μs|212ns|822ns|0.191| 0|0|20.14&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`SendRequest`|net472|0ns|0ns|0ns|0| 0|0|0&nbsp;b|
|#4531|`SendRequest`|net6.0|169μs|144ns|559ns|0.254| 0|0|18.08&nbsp;KB|
|#4531|`SendRequest`|netcoreapp3.1|189μs|264ns|1.02μs|0.189| 0|0|20.14&nbsp;KB|
|#4531|`SendRequest`|net472|0.000871ns|0.000239ns|0.000863ns|0| 0|0|0&nbsp;b|
</details>


<details><summary><strong>Benchmarks.Trace.CIVisibilityProtocolWriterBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`WriteAndFlushEnrichedTraces`|net6.0|529μs|308ns|1.19μs|0.541| 0|0|41.61&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|622μs|1.41μs|5.45μs|0.312| 0|0|41.6&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`WriteAndFlushEnrichedTraces`|net472|765μs|2.67μs|10.3μs|8.38| 2.67|0.381|53.24&nbsp;KB|
|#4531|`WriteAndFlushEnrichedTraces`|net6.0|499μs|772ns|2.99μs|0.504| 0|0|41.52&nbsp;KB|
|#4531|`WriteAndFlushEnrichedTraces`|netcoreapp3.1|633μs|719ns|2.79μs|0.309| 0|0|41.72&nbsp;KB|
|#4531|`WriteAndFlushEnrichedTraces`|net472|776μs|1.72μs|6.45μs|8.06| 2.42|0.403|53.23&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.DbCommandBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`ExecuteNonQuery`|net6.0|1.05μs|0.367ns|1.42ns|0.0104| 0|0|768&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`ExecuteNonQuery`|netcoreapp3.1|1.3μs|0.599ns|2.24ns|0.0105| 0|0|768&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`ExecuteNonQuery`|net472|1.66μs|0.738ns|2.66ns|0.116| 0|0|730&nbsp;B|
|#4531|`ExecuteNonQuery`|net6.0|1.05μs|0.157ns|0.588ns|0.0107| 0|0|768&nbsp;B|
|#4531|`ExecuteNonQuery`|netcoreapp3.1|1.31μs|0.195ns|0.674ns|0.0105| 0|0|768&nbsp;B|
|#4531|`ExecuteNonQuery`|net472|1.57μs|0.343ns|1.28ns|0.116| 0|0|730&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.ElasticsearchBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #4531

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.ElasticsearchBenchmark.CallElasticsearch&#8209;net472 | 1.137 | 2,276.51 | 2,588.74 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`CallElasticsearch`|net6.0|1.15μs|0.354ns|1.33ns|0.0137| 0|0|992&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`CallElasticsearch`|netcoreapp3.1|1.44μs|0.643ns|2.41ns|0.0131| 0|0|992&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`CallElasticsearch`|net472|2.28μs|1.17ns|4.54ns|0.159| 0.00114|0|1&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`CallElasticsearchAsync`|net6.0|1.21μs|0.447ns|1.67ns|0.0137| 0|0|968&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`CallElasticsearchAsync`|netcoreapp3.1|1.54μs|0.859ns|3.33ns|0.0138| 0|0|1.04&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`CallElasticsearchAsync`|net472|2.6μs|0.778ns|3.01ns|0.168| 0|0|1.06&nbsp;KB|
|#4531|`CallElasticsearch`|net6.0|1.27μs|0.466ns|1.8ns|0.0138| 0|0|992&nbsp;B|
|#4531|`CallElasticsearch`|netcoreapp3.1|1.4μs|0.611ns|2.2ns|0.0133| 0|0|992&nbsp;B|
|#4531|`CallElasticsearch`|net472|2.59μs|2.18ns|8.44ns|0.159| 0.00129|0|1&nbsp;KB|
|#4531|`CallElasticsearchAsync`|net6.0|1.27μs|0.503ns|1.88ns|0.014| 0|0|968&nbsp;B|
|#4531|`CallElasticsearchAsync`|netcoreapp3.1|1.55μs|1.1ns|4.12ns|0.014| 0|0|1.04&nbsp;KB|
|#4531|`CallElasticsearchAsync`|net472|2.53μs|0.428ns|1.66ns|0.168| 0.00126|0|1.06&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.GraphQLBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`ExecuteAsync`|net6.0|1.37μs|0.652ns|2.44ns|0.0124| 0|0|912&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`ExecuteAsync`|netcoreapp3.1|1.43μs|0.621ns|2.41ns|0.0122| 0|0|912&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`ExecuteAsync`|net472|1.65μs|0.957ns|3.71ns|0.139| 0|0|875&nbsp;B|
|#4531|`ExecuteAsync`|net6.0|1.25μs|0.941ns|3.52ns|0.0131| 0|0|912&nbsp;B|
|#4531|`ExecuteAsync`|netcoreapp3.1|1.45μs|0.474ns|1.84ns|0.0123| 0|0|912&nbsp;B|
|#4531|`ExecuteAsync`|net472|1.71μs|0.822ns|3.18ns|0.139| 0.000853|0|875&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.HttpClientBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`SendAsync`|net6.0|3.9μs|0.841ns|3.15ns|0.0274| 0|0|1.94&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`SendAsync`|netcoreapp3.1|4.5μs|3ns|11.2ns|0.0337| 0|0|2.48&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`SendAsync`|net472|7.07μs|3.35ns|12.5ns|0.483| 0|0|3.05&nbsp;KB|
|#4531|`SendAsync`|net6.0|3.76μs|2.08ns|7.8ns|0.0263| 0|0|1.94&nbsp;KB|
|#4531|`SendAsync`|netcoreapp3.1|4.65μs|1.66ns|6.19ns|0.0326| 0|0|2.48&nbsp;KB|
|#4531|`SendAsync`|net472|7.13μs|2.14ns|8.28ns|0.483| 0|0|3.05&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.ILoggerBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`EnrichedLog`|net6.0|1.31μs|0.698ns|2.7ns|0.0228| 0|0|1.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`EnrichedLog`|netcoreapp3.1|1.94μs|0.707ns|2.64ns|0.0223| 0|0|1.62&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`EnrichedLog`|net472|2.39μs|1.2ns|4.14ns|0.244| 0|0|1.54&nbsp;KB|
|#4531|`EnrichedLog`|net6.0|1.38μs|0.342ns|1.28ns|0.0229| 0|0|1.62&nbsp;KB|
|#4531|`EnrichedLog`|netcoreapp3.1|1.87μs|1.69ns|6.54ns|0.0214| 0|0|1.62&nbsp;KB|
|#4531|`EnrichedLog`|net472|2.28μs|3.27ns|12.7ns|0.244| 0|0|1.54&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.Log4netBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`EnrichedLog`|net6.0|114μs|113ns|439ns|0.0562| 0|0|4.21&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`EnrichedLog`|netcoreapp3.1|118μs|189ns|730ns|0.0588| 0|0|4.21&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`EnrichedLog`|net472|148μs|180ns|699ns|0.658| 0.219|0|4.38&nbsp;KB|
|#4531|`EnrichedLog`|net6.0|110μs|91.5ns|343ns|0.0556| 0|0|4.21&nbsp;KB|
|#4531|`EnrichedLog`|netcoreapp3.1|118μs|234ns|907ns|0| 0|0|4.21&nbsp;KB|
|#4531|`EnrichedLog`|net472|148μs|260ns|1.01μs|0.665| 0.222|0|4.38&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.NLogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`EnrichedLog`|net6.0|2.82μs|1.14ns|4.42ns|0.0295| 0|0|2.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`EnrichedLog`|netcoreapp3.1|3.9μs|2.93ns|10.6ns|0.0291| 0|0|2.18&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`EnrichedLog`|net472|4.56μs|1.09ns|4.23ns|0.315| 0|0|1.99&nbsp;KB|
|#4531|`EnrichedLog`|net6.0|2.77μs|0.83ns|3.11ns|0.0305| 0|0|2.18&nbsp;KB|
|#4531|`EnrichedLog`|netcoreapp3.1|3.86μs|0.969ns|3.75ns|0.029| 0|0|2.18&nbsp;KB|
|#4531|`EnrichedLog`|net472|4.53μs|1.49ns|5.57ns|0.315| 0|0|1.99&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.RedisBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`SendReceive`|net6.0|1.31μs|1.19ns|4.59ns|0.0164| 0|0|1.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`SendReceive`|netcoreapp3.1|1.64μs|0.326ns|1.18ns|0.0155| 0|0|1.16&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`SendReceive`|net472|2.04μs|2.15ns|7.76ns|0.184| 0|0|1.16&nbsp;KB|
|#4531|`SendReceive`|net6.0|1.29μs|0.963ns|3.6ns|0.0165| 0|0|1.16&nbsp;KB|
|#4531|`SendReceive`|netcoreapp3.1|1.61μs|0.658ns|2.37ns|0.0154| 0|0|1.16&nbsp;KB|
|#4531|`SendReceive`|net472|2.03μs|1.97ns|7.37ns|0.185| 0|0|1.16&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SerilogBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`EnrichedLog`|net6.0|2.45μs|1.04ns|3.91ns|0.0207| 0|0|1.53&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`EnrichedLog`|netcoreapp3.1|3.54μs|1.47ns|5.1ns|0.0217| 0|0|1.58&nbsp;KB|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`EnrichedLog`|net472|3.97μs|1.88ns|7.27ns|0.311| 0|0|1.96&nbsp;KB|
|#4531|`EnrichedLog`|net6.0|2.6μs|0.87ns|3.14ns|0.0207| 0|0|1.53&nbsp;KB|
|#4531|`EnrichedLog`|netcoreapp3.1|3.54μs|2.1ns|7.84ns|0.0214| 0|0|1.58&nbsp;KB|
|#4531|`EnrichedLog`|net472|4.09μs|0.899ns|3.48ns|0.309| 0|0|1.96&nbsp;KB|
</details>


<details><summary><strong>Benchmarks.Trace.SpanBenchmark</strong> - Same speed :heavy_check_mark: Same allocations :heavy_check_mark:

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`StartFinishSpan`|net6.0|445ns|0.106ns|0.398ns|0.0076| 0|0|536&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`StartFinishSpan`|netcoreapp3.1|520ns|0.203ns|0.76ns|0.00724| 0|0|536&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`StartFinishSpan`|net472|659ns|0.144ns|0.52ns|0.0852| 0|0|538&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`StartFinishScope`|net6.0|517ns|0.142ns|0.533ns|0.00908| 0|0|656&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`StartFinishScope`|netcoreapp3.1|691ns|0.427ns|1.65ns|0.00872| 0|0|656&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`StartFinishScope`|net472|838ns|0.759ns|2.94ns|0.0979| 0|0|618&nbsp;B|
|#4531|`StartFinishSpan`|net6.0|442ns|0.184ns|0.712ns|0.00746| 0|0|536&nbsp;B|
|#4531|`StartFinishSpan`|netcoreapp3.1|562ns|0.373ns|1.29ns|0.00731| 0|0|536&nbsp;B|
|#4531|`StartFinishSpan`|net472|612ns|0.118ns|0.456ns|0.0854| 0|0|538&nbsp;B|
|#4531|`StartFinishScope`|net6.0|522ns|0.228ns|0.883ns|0.00918| 0|0|656&nbsp;B|
|#4531|`StartFinishScope`|netcoreapp3.1|675ns|0.627ns|2.43ns|0.00884| 0|0|656&nbsp;B|
|#4531|`StartFinishScope`|net472|899ns|0.659ns|2.46ns|0.0981| 0|0|618&nbsp;B|
</details>


<details><summary><strong>Benchmarks.Trace.TraceAnnotationsBenchmark</strong> - Slower :warning: Same allocations :heavy_check_mark:



#### Slower :warning: in #4531

|  Benchmark         | diff/base | Base Median (ns) | Diff Median (ns) | Modality   |
|:----------|-----------:|-----------:|--------:|--------:|
| Benchmarks.Trace.TraceAnnotationsBenchmark.RunOnMethodBegin&#8209;net6.0 | 1.145 | 568.85 | 651.37 | 

</summary>

### Raw results


|  Branch |                      Method |     Toolchain |     Mean | StdError |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------|---------------------------- |-------------- |---------:|---------:|--------:|-------:|------:|------:|----------:|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`RunOnMethodBegin`|net6.0|569ns|0.162ns|0.629ns|0.00921| 0|0|656&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`RunOnMethodBegin`|netcoreapp3.1|878ns|0.267ns|1ns|0.00888| 0|0|656&nbsp;B|
|[master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)|`RunOnMethodBegin`|net472|1.08μs|0.259ns|0.971ns|0.098| 0|0|618&nbsp;B|
|#4531|`RunOnMethodBegin`|net6.0|651ns|0.301ns|1.13ns|0.00917| 0|0|656&nbsp;B|
|#4531|`RunOnMethodBegin`|netcoreapp3.1|814ns|0.189ns|0.706ns|0.0088| 0|0|656&nbsp;B|
|#4531|`RunOnMethodBegin`|net472|1.02μs|0.298ns|1.11ns|0.0978| 0|0|618&nbsp;B|
</details>

**Comment by andrewlock** [comment]
## Throughput/Crank Report:zap:

Throughput results for AspNetCoreSimpleController comparing the following branches/commits:
- [This PR (4531)](https://github.com/DataDog/dd-trace-dotnet/tree/c012d7ee6f2f7d46f3b0a267d8fb2766f61799e6)
- [master](https://github.com/DataDog/dd-trace-dotnet/tree/bcde76a28eed8641cca52b0a5460d3b66facc470)
- [benchmarks/2.9.0](https://github.com/DataDog/dd-trace-dotnet/tree/89ae3f4ee7d85b824badda5873166707c9e560b4)
- [benchmarks/2.35.0](https://github.com/DataDog/dd-trace-dotnet/tree/8bf7761d3905dfd95a8b6fb7eac280bb46e80f0e)

Cases where throughput results for the PR are worse than latest master (5% drop or greater), results are shown in **red**.

Note that these results are based on a _single_ point-in-time result for each branch. For full results, see [one](https://ddstaging.datadoghq.com/dashboard/fnz-afi-c2i/apm-net-crank) of the [many](https://ddstaging.datadoghq.com/dashboard/c5g-i7d-kcy/ciapp-apm-net-throughput-tests), [many](https://ddstaging.datadoghq.com/dashboard/uxh-m8j-qhi/ciapp-apm-net-throughput-tests-kevin) dashboards!

```mermaid
gantt
    title Throughput Linux x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4531) (11.410M)   : 0, 11410031
    master (11.599M)   : 0, 11599108
    benchmarks/2.35.0 (11.286M)   : 0, 11286124
    benchmarks/2.9.0 (11.340M)   : 0, 11340003

    section Automatic
    This PR (4531) (7.842M)   : 0, 7842010
    master (8.210M)   : 0, 8209835
    benchmarks/2.35.0 (7.896M)   : 0, 7895806
    benchmarks/2.9.0 (8.046M)   : 0, 8045589

    section Trace stats
    master (8.324M)   : 0, 8324285
    benchmarks/2.35.0 (8.094M)   : 0, 8094160

    section Manual
    This PR (4531) (9.968M)   : 0, 9967742
    master (10.433M)   : 0, 10432715
    benchmarks/2.35.0 (10.040M)   : 0, 10039503

    section Manual + Automatic
    This PR (4531) (7.564M)   : 0, 7564147
    master (7.900M)   : 0, 7899883
    benchmarks/2.35.0 (7.802M)   : 0, 7801816

    section Version Conflict
    master (7.221M)   : 0, 7220750
    benchmarks/2.35.0 (7.049M)   : 0, 7048949

```
```mermaid
gantt
    title Throughput Linux arm64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4531) (9.732M)   : 0, 9731555
    master (9.585M)   : 0, 9585099
    benchmarks/2.35.0 (9.501M)   : 0, 9501288
    benchmarks/2.9.0 (9.551M)   : 0, 9551441

    section Automatic
    This PR (4531) (6.744M)   : 0, 6743809
    master (6.673M)   : 0, 6673018
    benchmarks/2.35.0 (6.767M)   : 0, 6766575

    section Trace stats
    master (6.748M)   : 0, 6748068
    benchmarks/2.35.0 (6.661M)   : 0, 6660561

    section Manual
    This PR (4531) (8.608M)   : 0, 8607949
    master (8.436M)   : 0, 8436132
    benchmarks/2.35.0 (8.558M)   : 0, 8558254

    section Manual + Automatic
    This PR (4531) (6.395M)   : 0, 6395089
    master (6.576M)   : 0, 6575639
    benchmarks/2.35.0 (6.400M)   : 0, 6399958

    section Version Conflict
    master (5.939M)   : 0, 5938843
    benchmarks/2.35.0 (5.919M)   : 0, 5918638

```
```mermaid
gantt
    title Throughput Windows x64 (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4531) (10.491M)   : 0, 10491497
    master (10.142M)   : 0, 10142184
    benchmarks/2.35.0 (10.347M)   : 0, 10346803
    benchmarks/2.9.0 (10.227M)   : 0, 10227003

    section Automatic
    This PR (4531) (7.454M)   : 0, 7454222
    master (7.491M)   : 0, 7490757
    benchmarks/2.35.0 (7.511M)   : 0, 7510624
    benchmarks/2.9.0 (7.513M)   : 0, 7512506

    section Trace stats
    master (7.401M)   : 0, 7401348
    benchmarks/2.35.0 (7.458M)   : 0, 7458340

    section Manual
    This PR (4531) (9.377M)   : 0, 9377443
    master (9.421M)   : 0, 9420636
    benchmarks/2.35.0 (9.236M)   : 0, 9235560

    section Manual + Automatic
    This PR (4531) (7.264M)   : 0, 7263868
    master (7.238M)   : 0, 7237643
    benchmarks/2.35.0 (7.270M)   : 0, 7270256

    section Version Conflict
    master (6.698M)   : 0, 6697964
    benchmarks/2.35.0 (6.716M)   : 0, 6715616

```
```mermaid
gantt
    title Throughput Linux x64 (ASM) (Total requests) 
    dateFormat  X
    axisFormat %s
    section Baseline
    This PR (4531) (7.595M)   : 0, 7595315
    master (7.371M)   : 0, 7370702
    benchmarks/2.35.0 (7.577M)   : 0, 7576613
    benchmarks/2.9.0 (7.821M)   : 0, 7821144

    section No attack
    This PR (4531) (2.220M)   : 0, 2220492
    master (2.114M)   : 0, 2114280
    benchmarks/2.35.0 (2.140M)   : 0, 2140072
    benchmarks/2.9.0 (3.238M)   : 0, 3238074

    section Attack
    This PR (4531) (1.722M)   : 0, 1722402
    master (1.675M)   : 0, 1674856
    benchmarks/2.35.0 (1.831M)   : 0, 1830708
    benchmarks/2.9.0 (2.533M)   : 0, 2532806

    section Blocking
    This PR (4531) (3.200M)   : 0, 3200373
    master (3.104M)   : 0, 3104161
    benchmarks/2.35.0 (3.696M)   : 0, 3696195

```

**Review by robertpi — APPROVED** [review]

File: tracer/test/Datadog.Trace.ClrProfiler.IntegrationTests/RuntimeMetricsTests.cs [hunk 2]
```diff
@@ -131,7 +131,11 @@ private void RunTest()
             var runtimeIsBuggy = !EnvironmentTools.IsWindows()
```
Comment (zacharycmontoya) [inline tracer/test/Datadog.Trace.ClrProfiler.IntegrationTests/RuntimeMetricsTests.cs:131]: Do you need to update this check too?
